### ISSUE TITLE
Unable to set oversampling via SoapyLMS7

### ISSUE THREAD

**Issue by mendenm** [myriadrf/LimeSuite#252]
The "writeSetting" interface in Settings.cpp of SoapyLMS7 has no apparent way to set the oversampling.  If it is acceptable to TPTB could someone please make an addition to this something like what I have pasted below?  This goes right at the bottom of writeSetting().  I have included my suggested addition, and then the last few remaining lines of the function for context.

Thanks.

 ```
   else if (key == "OVERSAMPLING")
    {
        std::unique_lock<std::recursive_mutex> lock(_accessMutex);
        lms7Device->SetRate(sampleRate, std::stoi(value));
    }
    else
    {
        uint16_t val = std::stoi(value);
        if (lms7Device->WriteParam(key,val,channel)!=-1)
            return;
        throw std::runtime_error("unknown setting key: "+key);
    }
}

```

**Comment by guruofquality** [comment]
I think that could work, it certainly doesnt hurt anything. Another idea (something I have done on other devices) is to set the master clock rate (setMasterClockRate()), and use that in setSampleRate to determine the desired oversample factor. Since these are related numbers anyway by a power of two.
